"""Core city data structures for Cyber City.

The model layer intentionally represents only fictional educational game data.
It does not store addresses, network ranges, credentials, or any real security
scan targets.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class BuildingType(str, Enum):
    """Available fictional buildings in the city simulator."""

    FIREWALL_TOWER = "Firewall Tower"
    TRAINING_ACADEMY = "Training Academy"
    DATA_LIBRARY = "Data Library"
    BACKUP_STATION = "Backup Station"
    INCIDENT_HQ = "Incident HQ"
    RESIDENTIAL_BLOCK = "Residential Block"


BUILDING_PROFILES: dict[BuildingType, dict[str, int | str]] = {
    BuildingType.FIREWALL_TOWER: {
        "defense": 8,
        "awareness": 2,
        "resilience": 4,
        "cost": 80,
        "description": "Reduces fictional saboteur pressure near civic services.",
    },
    BuildingType.TRAINING_ACADEMY: {
        "defense": 3,
        "awareness": 9,
        "resilience": 3,
        "cost": 65,
        "description": "Improves citizen awareness against trickster events.",
    },
    BuildingType.DATA_LIBRARY: {
        "defense": 4,
        "awareness": 4,
        "resilience": 6,
        "cost": 75,
        "description": "Stores civic knowledge and raises recovery readiness.",
    },
    BuildingType.BACKUP_STATION: {
        "defense": 2,
        "awareness": 3,
        "resilience": 9,
        "cost": 70,
        "description": "Restores fictional city services after simulated incidents.",
    },
    BuildingType.INCIDENT_HQ: {
        "defense": 6,
        "awareness": 5,
        "resilience": 7,
        "cost": 90,
        "description": "Coordinates purely fictional response drills.",
    },
    BuildingType.RESIDENTIAL_BLOCK: {
        "defense": 1,
        "awareness": 2,
        "resilience": 2,
        "cost": 25,
        "description": "Adds citizens and increases the need for education.",
    },
}


@dataclass(slots=True)
class Building:
    """A placed city building."""

    building_type: BuildingType
    row: int
    column: int
    name: str | None = None

    @property
    def defense(self) -> int:
        return int(BUILDING_PROFILES[self.building_type]["defense"])

    @property
    def awareness(self) -> int:
        return int(BUILDING_PROFILES[self.building_type]["awareness"])

    @property
    def resilience(self) -> int:
        return int(BUILDING_PROFILES[self.building_type]["resilience"])

    @property
    def display_name(self) -> str:
        return self.name or self.building_type.value

    def to_dict(self) -> dict[str, Any]:
        return {
            "building_type": self.building_type.value,
            "row": self.row,
            "column": self.column,
            "name": self.name,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Building":
        return cls(
            building_type=BuildingType(data["building_type"]),
            row=int(data["row"]),
            column=int(data["column"]),
            name=data.get("name"),
        )


@dataclass(slots=True)
class IncidentReport:
    """A fictional event report generated by the simulator."""

    actor: str
    target: str
    risk_delta: int
    lesson: str


@dataclass(slots=True)
class CityMap:
    """Grid-backed city map containing placed buildings."""

    rows: int = 8
    columns: int = 10
    buildings: list[Building] = field(default_factory=list)

    def building_at(self, row: int, column: int) -> Building | None:
        return next(
            (building for building in self.buildings if building.row == row and building.column == column),
            None,
        )

    def place_building(self, building_type: BuildingType, row: int, column: int) -> Building:
        if not self._is_inside_grid(row, column):
            raise ValueError("Building placement is outside the city grid.")
        existing = self.building_at(row, column)
        if existing is not None:
            self.buildings.remove(existing)
        building = Building(building_type=building_type, row=row, column=column)
        self.buildings.append(building)
        return building

    def remove_building(self, row: int, column: int) -> None:
        existing = self.building_at(row, column)
        if existing is not None:
            self.buildings.remove(existing)

    def city_score(self) -> dict[str, int]:
        defense = sum(building.defense for building in self.buildings)
        awareness = sum(building.awareness for building in self.buildings)
        resilience = sum(building.resilience for building in self.buildings)
        population_pressure = sum(
            4 for building in self.buildings if building.building_type is BuildingType.RESIDENTIAL_BLOCK
        )
        risk = max(0, 100 - defense * 2 - awareness - resilience + population_pressure)
        return {
            "defense": defense,
            "awareness": awareness,
            "resilience": resilience,
            "risk": min(100, risk),
        }

    def to_dict(self) -> dict[str, Any]:
        return {
            "rows": self.rows,
            "columns": self.columns,
            "buildings": [building.to_dict() for building in self.buildings],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CityMap":
        city = cls(rows=int(data.get("rows", 8)), columns=int(data.get("columns", 10)))
        city.buildings = [Building.from_dict(item) for item in data.get("buildings", [])]
        return city

    def _is_inside_grid(self, row: int, column: int) -> bool:
        return 0 <= row < self.rows and 0 <= column < self.columns
